- name: DevOps Mid Project Deployment
  hosts: localhost
  connection: local
  become: true

  vars:
    ghcr_username: "{{ github_actor }}"
    ghcr_token: "{{ github_token }}"

  tasks:
    - name: Install Docker and Compose plugin
      dnf:
        name:
          - docker
          - docker-compose-plugin
        state: present
      ignore_errors: yes

    - name: Ensure Docker service is running
      service:
        name: docker
        state: started
        enabled: true

    - name: Add user to docker group
      user:
        name: "{{ ansible_user_id }}"
        groups: docker
        append: yes
      ignore_errors: yes

    - name: Login to GitHub Container Registry
      docker_login:
        registry_url: ghcr.io
        username: "{{ ghcr_username }}"
        password: "{{ ghcr_token }}"

    - name: Deploy application using Docker Compose
      command: docker compose up -d --build --force-recreate
      args:
        chdir: "{{ playbook_dir }}"
      environment:
        MYSQL_ROOT_PASSWORD: "{{ mysql_root_password }}"
        DB_PASSWORD: "{{ mysql_root_password }}"
        DB_NAME: "{{ db_name }}"
        DB_USER: "{{ db_user }}"
        DB_PORT: "{{ db_port }}"
        DB_HOST: "{{ db_host }}"
        GITHUB_ACTOR: "{{ github_actor }}"